name: Beacon
options:
  bundleIdPrefix: com.beacon
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    GENERATE_INFOPLIST_FILE: "YES"

targets:
  Beacon:
    type: application
    platform: iOS
    sources:
      - Beacon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beacon.app
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_CFBundleDisplayName: Beacon
        SWIFT_EMIT_LOC_STRINGS: "YES"

  BeaconTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - BeaconTests
    dependencies:
      - target: Beacon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beacon.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Beacon.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Beacon"
        BUNDLE_LOADER: "$(TEST_HOST)"

  BeaconUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - BeaconUITests
    dependencies:
      - target: Beacon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beacon.app.uitests
        TEST_TARGET_NAME: Beacon
